# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6".device = "/dev/disk/by-uuid/21aed1d9-f018-41ba-98c4-5e3900da5ec6";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2119-813F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # ── Swap ────────────────────────────────────────────────────────────────────
  # Hand-edited, deliberately, despite the generated-file banner above.
  #
  # nixos-generate-config wrote this as the mapper that happened to be open at
  # install time — /dev/mapper/luks-60b43e2c-… — but it only emits
  # boot.initrd.luks.devices for containers needed to reach *root*, so nothing
  # ever opened this one. The swap unit has been waiting on a device node that is
  # never created, silently, since install.
  #
  # Confirmed on the running host 2026-08-08 rather than inferred: `swapon --show`
  # printed nothing, `free -h` reported `Swap: 0B` against 31 GiB of RAM, and
  # `lsblk` showed nvme0n1p3 as bare `crypto_LUKS` with no `crypt` child while
  # nvme0n1p2 showed its own. See hosts/memory-alpha/HARDWARE-MAP.md §2.
  #
  # randomEncryption keys the swap afresh from /dev/urandom on every boot, so it
  # needs no passphrase and no keyfile. That matters specifically here: this host
  # unlocks remotely over initrd SSH and the whole design assumes a single prompt,
  # which declaring a second LUKS container in initrd would have broken. The cost
  # is hibernation, which a headless server does not use.
  #
  # ⚠ This points at the RAW partition, not the old mapper. The stale LUKS header
  # is overwritten on first activation — free, since swap contents are worthless
  # by definition — but it does mean the path must be right. Verified on the host
  # 2026-08-09 rather than trusted: `ls -l /dev/disk/by-id/` resolves this link to
  # nvme0n1p3, the same partition HARDWARE-MAP.md §2 caught sitting idle. by-id is
  # stable across reboots and recabling in a way /dev/nvme0n1p3 is not.
  #
  # udev also emits a duplicate `…_PNY21232106090100590_1-part3` alias for this
  # partition — a known NVMe by-id name collision it disambiguates with a suffix.
  # Harmless here because there is one disk, so both names land on nvme0n1p3. It
  # would matter on a machine holding two disks that share a model and serial,
  # where the suffix separates different hardware and the assignment can flip.
  swapDevices =
    [ { device = "/dev/disk/by-id/nvme-PNY_CS2130_1TB_SSD_PNY21232106090100590-part3";
        randomEncryption.enable = true;
      }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
