# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6".device = "/dev/disk/by-uuid/21aed1d9-f018-41ba-98c4-5e3900da5ec6";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2119-813F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # ── Swap ────────────────────────────────────────────────────────────────────
  # Hand-edited, deliberately, despite the generated-file banner above: the
  # generator wrote a LUKS mapper nothing ever opened (it only emits initrd
  # openers for containers needed to reach *root*), so the host silently ran
  # swapless. This points at the RAW partition via its stable by-id path, and
  # randomEncryption rekeys it from /dev/urandom each boot — no passphrase, so
  # the initrd SSH unlock stays a single prompt; the cost is hibernation,
  # which a headless server does not use. Full story + host verification:
  # hosts/memory-alpha/HARDWARE-MAP.md §2. Re-apply this block if the file is
  # ever regenerated.
  swapDevices =
    [ { device = "/dev/disk/by-id/nvme-PNY_CS2130_1TB_SSD_PNY21232106090100590-part3";
        randomEncryption.enable = true;
      }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
