# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6".device = "/dev/disk/by-uuid/21aed1d9-f018-41ba-98c4-5e3900da5ec6";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-21aed1d9-f018-41ba-98c4-5e3900da5ec6";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2119-813F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-60b43e2c-62be-4e50-b590-190241219796"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
